conn.go
link.go

I also recommend using the fully-qualified imports path.  Makes things easier.  Do you have some `$GOROOT` magic set up right now?
This fixes both the available functions as far as I can tell.  Package `netlink` also handles multi-part messages properly now and trims the last one off so the caller doesn't have to.

rtnetlink: fix a couple netlink usage problems

---

link.go

This was a common enough pattern that I decided to just add it directly to `nlenc`.

rtnetlink: use new nlenc.Uint{16,32}Bytes

---

link.go

Without calling receive on the netlink socket, we never get error
messages (such as EEXIST or EOPNOTSUPP) from the kernel rtnetlink
implementation. Without these errors, applications using LinkService may
continue with the assumption no errors occurred.
This change modifies the LinkService implementation to call the netlink
library's Execute method, which both sends our message, as well as
receives the response.
This change also modifies the message sent by New to be of type
RTM_NEWLINK, so the kernel knows to create a new link.

fix(LinkService): execute to get errors from netlink

---

.travis.yml

Installs golint from the canonical location to satisfy go-get checks
from tip.

chore: install golint from canonical location

---

conn_test.go
link.go
link_test.go

Fixes #18
When marshaling a LinkMessage the default values for LinkAttributes
causes netlink errors. By using a pointer to check if
LinkAttributes are set or not and only marshaling them if not nil
we prevent causing these errors.
Signed-off-by: Jeroen Simonetti <jeroen@simonetti.nl>

Dont marshal empty LinkAttributes

---

rtnl/addr.go
rtnl/conn.go
rtnl/link.go
rtnl/links_live_test.go
rtnl/neigh.go
rtnl/route.go

Initial pre-mature drop of the wrapper package; context in issue #40.
Based on the [godoc examples](https://godoc.org/github.com/jsimonetti/rtnetlink) and parts of the [u-root pull request 1187](https://github.com/u-root/u-root/pull/1187).
@insomniacslk @jsimonetti @mdlayher

add rtnl, the new high-level wrapper package

---

rtnl/conn.go

As discussed under issue #40, it is a rather good tone to leave up to the caller to decide whether an error in Close() is a relevant factor for them.

rtnl: do not drop error on Close() but leave to caller

---

rtnl/route.go

Added `RouteDel` to support route deletion.
Also added `RouteAddSrc` to support adding routes with a source parameter.
Signed-off-by: Andrea Barberio <insomniac@slackware.it>

[rtnl] Add RouteDel and RouteAddSrc

---

rtnl/route.go

As discussed on https://github.com/jsimonetti/rtnetlink/pull/47
Signed-off-by: Andrea Barberio <insomniac@slackware.it>

[rtnl] Remove unnecessary parameters from RouteDel

---

example_address_add_test.go
example_address_del_test.go
rtnl/addr.go
rtnl/addr_live_test.go
rtnl/addr_test.go

Hi @jsimonetti, better late than never!
This addresses an issue I ran into while trying out `rtnl` and the base package. As promised, no existing behaviour or API was modified. I've added a small test suite that could use some more cases, but the code under test is quite limited.
Let me know if anything needs to be added or corrected.

rtnl.(Must)ParseAddr and documentation fixes

---

rtnl/addr.go

@jsimonetti Turns out host scope needs to be set explicitly when adding loopback addresses other than `127.0.0.1`. (strace shows `ifa_scope=RT_SCOPE_HOST,` when using `ip a add 127.0.1.1/8 dev lo`) 
`127.0.0.1` in particular might be hardcoded in the kernel, because sending `RT_SCOPE_LINK` works fine for that one. For anything else that starts with `127`, `RT_SCOPE_HOST` seems to be required.

rtnl - set 'host' scope when adding loopback addresses

---

link.go

In looking through the documentation and iproute2 code, `RTM_SETLINK`
seems to only be used in a handful of special cases, whereas `RTM_NEWLINK`
is used across the board for both new link creation as well as modification.
Example strace of setting bond mode: 
```
$ sudo strace -tt -e trace=sendmsg -v ip link set dev bond2 type bond mode 4 2>&1 
22:15:35.076608 sendmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000},
msg_namelen=12, msg_iov=[{iov_base={{len=56, type=RTM_NEWLINK, flags=NLM_F_REQUEST|NLM_F_ACK, 
seq=1573942536, pid=0}, ...
```
Signed-off-by: Brad Beam <brad.beam@talos-systems.com>

fix: Use correct message type for Set

---

conn.go
conn_test.go

Signed-off-by: Matt Layher <mdlayher@gmail.com>
This is necessary to enable unblocking a receive operation by setting a past deadline.

rtnetlink: expose Conn.SetReadDeadline

---

link.go

Hey,
In my project I needed to use the`link list` command to get network interfaces by a specific kind. 
With `iproute2` this is supported via `ip link list type <TYPE>`. 
This addition adds this capability via the `ListByKind` function, I left the existent `list` function intact and just wrapped my filtering around it. 
Let me know if there is anything else needed, thanks!

Add a filter by kind to the link list command

---

go.mod
go.sum
internal/unix/types_linux.go
internal/unix/types_other.go
route.go
route_test.go

Signed-off-by: Matt Layher <mlayher@fastly.com>
Supersedes #80 since I accidentally opened that PR off master, so I can use my fork elsewhere with Go modules.

rtnetlink: add RouteMetrics nested attributes within RouteAttributes

---

go.sum
rtnl/route.go
rtnl/route_options.go

This PR will add the ability to use functional args for route
add/replace with rtnl. Currently, two functions are supported,
`WithRouteSrc` and `WithRouteAttrs`. This allows the consolidation of
the route methods, as well as adding the ability to BYO-Attributes for a
given route. This layout can of course be extended to add other
route-specific args, as well as a starting point for options and args for other parts of the
rtnl package as time goes on.
Note that this removes the `RouteAddSrc` and `RouteReplaceSrc`
functions.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

[rtnl] support functional args for routes

---

internal/unix/types_linux.go
internal/unix/types_other.go
route.go
route_test.go

Co-authored by @djosephsen, and supersedes #82. Will squash on approval.
I've tested this successfully in an environment using multipath nexthop attributes.

rtnetlink: complete route multipath encoding and decoding logic

---

route.go
route_test.go

Signed-off-by: Matt Layher <mlayher@fastly.com>
One of the tests doesn't pass because I suspect I'm missing a To4 somewhere, but this is a step in the right direction.

rtnetlink: add encodeIP netlink attribute IP address helper

---

conn.go

Signed-off-by: Matt Layher <mdlayher@gmail.com>
We're on netlink v1.4.1 and already dropped support for old Go as of v1.2.0 there.

rtnetlink: remove outdated Go version warning on Conn.SetReadDeadline

---

address.go
address_test.go
example_address_add_test.go
example_address_del_test.go
rtnl/addr.go

Signed-off-by: Matt Layher <mdlayher@gmail.com>
I need the ability to completely omit the address attributes structure when filtering addresses by interface with strict checking enabled. Currently the marshaling code reports an error due to the empty attributes:
```
netlink receive: invalid argument, offset: 0, message: "Unknown attribute type"
```
Although this is a minor breaking change, we haven't tagged a stable release and it seems necessary to fix this now in order to enable better flexibility in tandem with strict checking enabled.
Updates #121.

rtnetlink: make AddressMessage.Attributes optional via pointer

---

internal/unix/types_linux.go
internal/unix/types_other.go
route.go
route_test.go

Signed-off-by: Matt Layher <mdlayher@gmail.com>
Another optional one because the zero value "medium" pref cannot be set in strict check dump requests.

rtnetlink: support for RTA_PREF

---

example_link_setdown_test.go
example_link_sethwaddr_test.go
example_link_setup_test.go
rtnl/link.go

Currently LinkUp/LinkDown fails to work on some network cards with EINVAL, as `rx.Family` is not always `AF_UNSPEC`. Passing AF_UNSPEC explicitly seems to be safe, it's also used by [vishvananda/netlink](https://github.com/vishvananda/netlink/blob/7b913bc23ecb7f817bebf8ac50fe1ef1b9d36799/link_linux.go#L376-L413).
Let's make this comment true :smile::
https://github.com/jsimonetti/rtnetlink/blob/896a1067bb59d587f6588a00916d7b490398d173/link.go#L24-L26

Fix invalid LinkMessage family

---

link.go
link_test.go

* Add the value received to make it easier to debug.
* Include the message type in the error.
Signed-off-by: SuperQ <superq@gmail.com>

Improve LinkStats error message

---

neigh.go

As per definition of ndmsg in kernel source:
```c
struct ndmsg {
__u8		ndm_family;
__u8		ndm_pad1;
__u16		ndm_pad2;
__s32		ndm_ifindex;
__u16		ndm_state;
__u8		ndm_flags;
__u8		ndm_type;
};
```

Address family is a u8, not u16

---

neigh.go
neigh_test.go

The kernel sometimes returns empty LLAddress in NeighAttributes. Allow this to be returned as a nil address.
Fixes: https://github.com/jsimonetti/rtnetlink/issues/199

Allow empty neighbor LLAddress

---

driver/bond_live_test.go
driver/driver_test.go
driver/netkit_live_test.go
driver/veth_live_test.go
internal/testutils/netns.go
internal/testutils/version.go
internal/unix/types_linux.go
internal/unix/types_other.go
link.go
link_live_test.go
netns.go
rtnl/neigh.go
rtnl/neigh_live_test.go

Please see individual commits for the reasoning behind every change. I did some drive-by cleaning on the more obvious things I could fix quickly, driven by lessons learned working on other libraries.
Please let me know if this should be split up. Most of the changes are in testing and they follow logically, so I thought they made sense as a single PR.

Refactor netns handling, fix flakes, namespace some tests

---

internal/unix/types_linux.go
internal/unix/types_other.go
link.go

This properly list is used e.g. by `systemd-udevd` to provide other alternative names for predictable interface names.

feat: implement support for altnames

---

link.go

To make it a bit more symmetric with retrieving information.
Note: this only works for `.Set()`, not `.New()`.

feat: support setting alias for links

---

conn.go
link.go
link_live_test.go

the linux kernel handles a RTM_GETLINK request even in case of incorrent kind filter. if it finds requested kind it responds with a list of this kind of links and marks every message in a response by NLM_F_DUMP_FILTERED flag. Otherwise it sends all available links w/o NLF_F_DUMP_FILTERED. So, looks much better to return to a callee empty link list if there are no links of requested kind.

rtnetlink: fix Link ListByKind response

---

address.go
internal/unix/types_linux.go
internal/unix/types_other.go

This allows to set route priority/metric for prefix routes created automatically when an address is assigned.
E.g. `10.0.0.0/8` with metric `32` would generate a route:
```
10.0.0.0/8 via <if> metric 32
```
The default metric is zero. A custom metric allows to prefer one interface over another when the prefixes overlap.
See https://github.com/siderolabs/talos/issues/10696

feat: add support for address priority

---

route.go
route_live_test.go

A new "ListMatch" function has been added to the RouteService to allow for kernel-based filtering of the routing tables. The netlink flags required for getting a route for an IP (eg, rtnl.RouteGetAll) is different than those required while filtering the table.
This changeset removes the superfluous "netlink.DumpFiltered" flag from the Get function of RouteService, as this flag is for kernel responses.

feat(route): list with kernel filtering
